version: "3"
services:
  app:
    container_name: effectiveOfficeBackend
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db_postgres
    profiles:
      - dev

  db_postgres:
    container_name: postgresForKtor
    image: postgres:15.2-alpine
    volumes:
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_DB=effectiveOfficeBackendDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234567890
    ports:
      - "15432:5432"
    restart: 'no'